version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_credit_db
    restart: always
    ports:
      - "27003:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongo_data: